POST http://localhost:4000/app/SignupSection
Content-Type: application/json

{
    "fullName":"Joseph Omotosho",
    "Email":"Joseph.omotosho98@gmail.com",
    "password":"chiwagonu",
    "confirmpassword":"chiwagonu"
    
}





#In the above we are trying to mimic a post request since we do not have a front end yet.
#even if you do have a front end, you can mimic your request for testing sake
# the link in front of the POST is called an endpoint, thats where the post request gets sent to